### ISSUE TITLE
A few changes:

### ISSUE THREAD

**Issue by dasu** [afengg/twitch.py#1]
uncomment the lines after the two excepts around line 126~,
Remove the floating sopel rule that's not attached to anything at the bottom of the script.

a new issue with latest script:
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/dist-packages/sopel/tools/jobs.py", line 142, in _call
    func(self.bot)
  File "/home/desu/.sopel/modules/twitch.py", line 131, in monitor_streamers
    for hstreamer in smash_gen:
  File "/home/desu/.sopel/modules/twitch.py", line 77, in smash_generator
    for streamer in streaming['livestream']:
NameError: global name 'streaming' is not defined

every 10s...

**Comment by afengg** [comment]
resolved, thanks
